version: '3.5'

services:
  protocols_db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=demo
      - POSTGRES_USER=demo
      - POSTGRES_PASSWORD=demo
    volumes:
      - ./db/1-create-tables.sql:/opt/1-create-tables.sql
      - ./sh:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432